name: Publish
run-name: ${{ github.actor }} is publishing a new version 🚀
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of update'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - rc
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn build-storybook
      - run: yarn deploy --type=${{ inputs.type }}
      - run: yarn deploy-storybook